### ISSUE TITLE
headwind not deploying with external prostgresql

### ISSUE THREAD

**Issue by h0jeZvgoxFepBQ2C** [christianhuth/helm-charts#1169]
```yaml
adminEmail: technik@mydomain.com
baseDomain: mydomain.com

postgresql:
  enabled: false


externalPostgresql:
  hostname: myhost.com
  port: 25060
  auth:
    database:     database123
    password:     password123
    username:     username123
    # existingSecret:
    # userPasswordKey:

headwind:
  sharedSecret:
    secretValue: secret123


ingress: 
  enabled: true
  className: "nginx"
  tls:
    - secretName: tls-domain
      hosts:
      - mydomain.com
      
  hosts:
    - host: "mydomain.com"
      paths:
        - path: /
          pathType: ImplementationSpecific
persistence:
  enabled: true
  storageClass: do-block-storage


```

leads to?

```log
grep: /usr/local/tomcat/work/init1.sql: No such file or directory
cat: /usr/local/tomcat/work/init1.sql: No such file or directory
rm: cannot remove '/usr/local/tomcat/work/init1.sql': No such file or directory
Can't open /privkey.pem for reading, No such file or directory
140141809620288:error:02001002:system library:fopen:No such file or directory:../crypto/bio/bss_file.c:69:fopen('/privkey.pem','r')
140141809620288:error:2006D080:BIO routines:BIO_new_file:no such file:../crypto/bio/bss_file.c:76:
unable to load private key
Importing keystore /usr/local/tomcat/ssl/hmdm.p12 to /usr/local/tomcat/ssl/hmdm.jks...
keytool error: java.io.FileNotFoundException: /usr/local/tomcat/ssl/hmdm.p12 (No such file or directory)
```
