### ISSUE TITLE
[umami] Allow user to mount custom umami script

### ISSUE THREAD

**Issue by svenikea** [christianhuth/helm-charts#1440]
### Is your feature request related to a problem ?

We cannot push the analytic data to our Umami server due to constraints in our Electron app, so we have to make some changes to the script in order for it to work properly.

### Describe the solution you'd like.

I would like to have an option to mount my custom umami script to `/app/public/script.js` as a configmap something like this 

deployment.yaml
```
{{ if .Values.customUmamiScript.enabled }}
    volumeMounts:
     - name: script
        mountPath: /app/public/script.js
        subPath: script.js
volumes:
- name: script
   configMap:
    name: umami-script
{{ end }}
```
configmap.yaml
```
{{ if .Values.customUmamiScript.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
 name: umami-script
data:
  script.js: |
    {{ .Values.customUmamiScript.data | nindent 4 }}
{{ end }}

```
values.yaml
```
customUmamiScript:
  enabled: false
  data:  ~
```

### Describe alternatives you've considered.

My team and I initially tried two solutions:
1. We copied the content of the /umami path and placed it in our source code to build, but it didn't work as expected.
2. We attempted to build a custom image, but that would incur additional maintenance overhead.
3. We uploaded the custom script to a CDN endpoint, and reroute the location `/umami` to that CDN endpoint. But if the custom script is updated, we have to purge the cache so it can reflect the new content which takes several minutes, not to mention on device local cache
