### ISSUE TITLE
[all] Add support link to GitHub Issues

### ISSUE THREAD

**Issue by christianhuth** [christianhuth/helm-charts#1632]
### Is your feature request related to a problem ?

```yaml
  artifacthub.io/links: |
    - name: support
      url: https://github.com/christianhuth/helm-charts/issues
```

support: when a link named support is provided, a link to report an issue will be displayed highlighted on the package view.

### Describe the solution you'd like.

None

### Describe alternatives you've considered.

None
